---
title: "Wonderful Wednesdays Overview"
description: |
  This provides a short overview of our Wonderful Wednesdays Webinars.
author:
  - name: VIS SIG
    url: https://www.psiweb.org/sigs-special-interest-groups/visualisation
date: 03-12-2020
categories:
  - Wonderful Wednesdays
  - Overview
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Learn and Apply Key Principles of Data Visualisations
The data visualization special interest group (VIS SIG) was recently founded under the umbrella of EFSPI and PSI. Learn more about the VIS SIG.

The SIG is happy to introduce a new initiative called "[Wonderful Wednesdays](https://www.psiweb.org/sigs-special-interest-groups/visualisation/welcome-to-wonderful-wednesdays)". This initiative will provide the participants to not only learn theoretically about visualisation principles but also apply them to relevant examples from the field of healthcare and the development of new therapies. 

Inspired by 'Makeover Monday' and 'Tidy Tuesday', we will present on a monthly basis a data set reflecting the properties of a usual data set from a clinical trial or some other relevant study. This data set will come along with a description of the objectives for the data visualisation and relevant background information. 

Now the audience can share how they would visually communicate the objectives of the data set and submit the visualisation (along with the code) to receive feedback from the SIG members. Both, the presentation of the dataset and the visualisation as well as the feedback will be given in webinars. These 60 minutes webinars will occur every 2nd Wednesday of the month at 5pm CET. 

In the first webinar you will learn about visualization principles by visualization experts being active in the SIG. In addition, we will discuss the first visualization to improve on. 

Please find below the timelines for the next cycle:
* Webinar to present the case study: July 8th
* Timeline to submit improved visualizations: August 5th
* Webinar to provide feedback on the submitted visualizations: August 12th 

You will be able to submit your improvements for feedback via a Google Form on the homepage of the SIG after the webinar. These submissions need to include code (which is well documented and executable) as well as the file of the visualization itself.

# Data Submission

The data can be accessed and downloaded via this link:
https://github.com/VIS-SIG/Wonderful-Wednesdays.
Please submit your material via this Google Form. 

We will make the submissions available to the community together with highlights of the strength and limitations. Over time, this will lead to a gallery of visualizations for others to learn from.